#!/usr/bin/env bash
set -euo pipefail

# docker ps에서 lite 네이밍/네트워크 자동 탐지 후 00_env_local.sh 생성
BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$BASE/00_env_local.sh"

# 1) 이름 후보 수집
NAMES=$(docker ps --format '{{.Names}}' | tr -d '\r')
pick_by() { echo "$NAMES" | tr '[:upper:]' '[:lower:]' | grep -E "$1" | head -n1; }

GCS=$(pick_by '(^|-)g(round|cs|round-control|cs)(-|$)|ground-control-station|gcs') || true
[ -z "${GCS:-}" ] && GCS=$(pick_by 'ground.*lite|gcs.*lite') || true

CC=$(pick_by 'companion') || true
[ -z "${CC:-}" ] && CC=$(pick_by 'companion.*lite') || true

FC=$(pick_by 'flight(-|_)controller|fc') || true
[ -z "${FC:-}" ] && FC=$(pick_by 'flight.*lite') || true

SIM=$(pick_by 'simulator|sim$') || true
[ -z "${SIM:-}" ] && SIM=$(pick_by 'simulator.*lite') || true

# 2) 네트워크 이름(대부분 동일) 추출: 가장 많이 쓰이는 네트워크를 채택
NETS=$(docker ps --format '{{.Names}}\t{{.Networks}}' | awk '{print $2}' | tr ',' '\n' | sed '/^$/d')
DVD_NET=$(echo "$NETS" | sort | uniq -c | sort -nr | awk '{print $2}' | head -n1)

# 3) 파일 생성
cat > "$OUT" <<EOF
# Autogenerated by scripts/dvd_detect.sh
export DVD_C_GCS="${GCS}"
export DVD_C_CC="${CC}"
export DVD_C_FC="${FC}"
export DVD_C_SIM="${SIM}"
export DVD_NET="${DVD_NET}"
EOF

echo "[detect] wrote $OUT"
echo "[detect] values:"
cat "$OUT"
