# Autogenerated by scripts/dvd_detect.sh
export DVD_C_GCS="ground-control-station-lite"
export DVD_C_CC="companion-computer-lite"
export DVD_C_FC="flight-controller-lite"
export DVD_C_SIM="simulator-lite"
export DVD_NET="simulator"
