_wandb:
    value:
        cli_version: 0.23.0
        e:
            ekwjcss5ytj2820999gj40uxz7x0quqw:
                args:
                    - --level
                    - L0
                    - --config
                    - mtd/configs/iptables_mtd.yaml
                    - --interval
                    - "8"
                    - --wandb_project
                    - mtd_testbed_live
                    - --wandb_group
                    - vs_L0_Seeker
                codePath: dvd_lite/dvd_attacks_lpc/mtd/seeker.py
                codePathLocal: mtd/seeker.py
                cpu_count: 4
                cpu_count_logical: 4
                disk:
                    /:
                        total: "147469127680"
                        used: "84230189056"
                email: emforhsqhf29@gmail.com
                executable: /home/kali/MTD_full_testbed/dvd_lite/dvd_attacks_lpc/mtd_env/bin/python3
                git:
                    commit: c05fcc2708a155eb1b71ff9c6c3128db4be80a21
                    remote: https://github.com/PoppyPoppyPiggy/MTD_full_testbed
                host: kali
                memory:
                    total: "31390842880"
                os: Linux-6.12.38+kali-amd64-x86_64-with-glibc2.41
                program: /home/kali/MTD_full_testbed/dvd_lite/dvd_attacks_lpc/mtd/seeker.py
                python: CPython 3.13.7
                root: /home/kali/MTD_full_testbed/dvd_lite/dvd_attacks_lpc
                startedAt: "2025-11-12T07:53:42.426442Z"
                writerId: ekwjcss5ytj2820999gj40uxz7x0quqw
        m:
            - "1": global_step_time
              "6":
                - 3
              "7":
                - 2
        python_version: 3.13.7
        t:
            "3":
                - 2
                - 7
                - 13
                - 16
                - 63
            "4": 3.13.7
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
seeker_level:
    value: 0
